# Basic
title: Kyle_Ng
subtitle: 
welcome_message: welcome to my blog! 
description: prictice make perfect.
creator: <a href="https://kyleng.github.io">@Kyle_Ng</a>

url: "https://kyleng.github.io"

permalink: /:categories/:title

# Format
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 目录,        in_site: true,  description: 博客目录,       url: '/timeline'}
    - {title: 标签,        in_site: true,  description: 标签分类,       url: '/customview/CustomViewIndex'}
    - {title: 关于,        in_site: true,  description: 关于作者,       url: '/info/about'}
    


gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-redirect-from

# Pagination
paginate: 10
paginate_path: "page/:num/"

# Comment
comments :
  provider : duoshuo
  duoshuo :
    short_name : kyle
# Social
social:
    weibo: Kyle_Ng
    github: Kyle_Ng
    twitter: Kyle_Ng
#    rss: /feed.xml
    mail: Kyle_Ng
 #   copyright: http://choosealicense.online

# Google Analytics
ga:
#    id: UA-82493667-1
#    host: www.gcssloop.com
